import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

// NOTE: This file should be generated by running:
// flutterfire configure --project=your-firebase-project-id

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    if (defaultTargetPlatform == TargetPlatform.windows) {
      return windows;
    }
    if (defaultTargetPlatform == TargetPlatform.linux) {
      return linux;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'TODO_ANDROID_API_KEY',
    appId: 'TODO_ANDROID_APP_ID',
    messagingSenderId: 'TODO_MESSAGING_SENDER_ID',
    projectId: 'TODO_PROJECT_ID',
    databaseURL: 'TODO_DATABASE_URL',
    storageBucket: 'TODO_STORAGE_BUCKET',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TODO_IOS_API_KEY',
    appId: 'TODO_IOS_APP_ID',
    messagingSenderId: 'TODO_MESSAGING_SENDER_ID',
    projectId: 'TODO_PROJECT_ID',
    databaseURL: 'TODO_DATABASE_URL',
    storageBucket: 'TODO_STORAGE_BUCKET',
    iosBundleId: 'com.bokunokoto.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'TODO_WINDOWS_API_KEY',
    appId: 'TODO_WINDOWS_APP_ID',
    messagingSenderId: 'TODO_MESSAGING_SENDER_ID',
    projectId: 'TODO_PROJECT_ID',
    authDomain: 'TODO_AUTH_DOMAIN',
    databaseURL: 'TODO_DATABASE_URL',
    storageBucket: 'TODO_STORAGE_BUCKET',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'TODO_LINUX_API_KEY',
    appId: 'TODO_LINUX_APP_ID',
    messagingSenderId: 'TODO_MESSAGING_SENDER_ID',
    projectId: 'TODO_PROJECT_ID',
    databaseURL: 'TODO_DATABASE_URL',
    storageBucket: 'TODO_STORAGE_BUCKET',
  );
}
