default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>
  username: <%= ENV.fetch("DB_USERNAME", "bokunokoto") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>

development:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "bokunokoto_development") %>
  admin:
    <<: *default
    database: <%= ENV.fetch("ADMIN_DB_NAME", "bokunokoto_admin_development") %>
    migrations_paths: db/admin_migrate

test:
  primary:
    adapter: sqlite3
    database: storage/test.sqlite3
    pool: 5
  admin:
    adapter: sqlite3
    database: storage/admin_test.sqlite3
    pool: 5
    migrations_paths: db/admin_migrate

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "bokunokoto_production") %>
  admin:
    <<: *default
    database: <%= ENV.fetch("ADMIN_DB_NAME", "bokunokoto_admin_production") %>
    migrations_paths: db/admin_migrate
