default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>
  username: <%= ENV.fetch("DB_USERNAME", "bokunokoto") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "bokunokoto_development") %>

test:
  adapter: sqlite3
  database: storage/test.sqlite3
  pool: 5

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "bokunokoto_production") %>
